# Generated by Django 3.1.3 on 2023-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='null', upload_to='images'),
            preserve_default=False,
        ),
    ]
